#!/usr/bin/env python3
"""
Build the self-contained ConvertTools site.

Reads:   src/index.src.html, src/css/style.css, src/js/app.js, vendor/*.js
Writes:  index.html  — one single, fully self-contained file
         (CSS + all libraries + app code inlined; pdf.js worker ships
          inline as text and is started from a Blob URL at runtime)

Run:     python3 build-single.py
"""
import re
import pathlib

ROOT = pathlib.Path(__file__).parent
SRC = ROOT / "src"
VENDOR = ROOT / "vendor"

LIB_ORDER = [
    "pdf-lib.min.js",
    "pdf.min.js",
    "jszip.min.js",
    "mammoth.browser.min.js",
    "docx.umd.js",
    "html2pdf.bundle.min.js",
]
WORKER = "pdf.worker.min.js"


def prepare_js(text: str) -> str:
    """Make library source safe to inline inside <script> tags.

    The HTML parser treats <script> content as raw text with tricky rules:
      - "</script" ends the block (escape to "<\\/script"),
      - "<!--" pushes it into an "escaped" state where a following "<script"
        makes the REAL closing tag get ignored (double-escaped state).
    In JS, "<\\!--" evaluates identically to "<!--" inside strings/regex and
    is harmless in comments — so neutralizing it is the standard fix
    (same approach bundlers like Vite use when inlining scripts).
    """
    text = re.sub(r"\n?//# sourceMappingURL=[^\n]*", "", text)  # drop dead sourcemap refs
    text = re.sub(r"<!--", r"<\\!--", text)                     # defuse raw-text escaped state
    text = re.sub(r"</script", r"<\\/script", text, flags=re.IGNORECASE)
    assert "</script" not in text.lower(), "unescaped </script> in JS payload"
    assert "<!--" not in text, "unescaped <!-- in JS payload"
    return text


def main():
    html = (SRC / "index.src.html").read_text(encoding="utf-8")
    css = (SRC / "css" / "style.css").read_text(encoding="utf-8")
    app = (SRC / "js" / "app.js").read_text(encoding="utf-8")

    # ---- inline CSS ----
    link_tag = '<link rel="stylesheet" href="css/style.css" />'
    assert link_tag in html, "CSS link tag not found in template"
    html = html.replace(link_tag, "<style>\n" + css + "\n</style>")

    # ---- inline JS libraries ----
    chunks = []
    for name in LIB_ORDER:
        src = (VENDOR / name).read_text(encoding="utf-8")
        chunks.append("  <script>\n/* ===== vendor/%s (inlined) ===== */\n%s\n  </script>" % (name, prepare_js(src)))

    # ---- pdf.js worker as inline text (spun up from a Blob URL in app.js) ----
    worker_src = (VENDOR / WORKER).read_text(encoding="utf-8")
    chunks.append('  <script type="text/plain" id="ct-pdf-worker">\n%s\n  </script>' % prepare_js(worker_src))

    # ---- inline the app, last ----
    chunks.append("  <script>\n/* ===== ConvertTools app (inlined from src/js/app.js) ===== */\n%s\n  </script>" % prepare_js(app))

    script_block = "\n".join(chunks) + "\n"

    pattern = re.compile(
        r'  <!-- Libraries[^>]*-->\n(?:  <script src="[^"]+"></script>\n)+'
    )
    assert pattern.search(html), "external <script src=...> block not found in template"
    html = pattern.sub(lambda _m: script_block, html)  # literal replacement

    # ---- single-file build must allow inline scripts; broaden script-src only ----
    assert "script-src 'self'" in html, "CSP script-src not found"
    html = html.replace("script-src 'self'", "script-src 'unsafe-inline'")
    html = re.sub(
        r"<!-- Security:.*?-->",
        "<!-- Security: locked-down CSP — everything is same-origin, no plugins/objects/forms.\n"
        "       Single-file build: scripts are inlined, hence script-src 'unsafe-inline'.\n"
        "       See README.md for the full security model. -->",
        html,
        flags=re.DOTALL,
    )

    # ---- build banner ----
    banner = "<!--\n  ⚡ ConvertTools — single-file build\n" \
             "  Generated by build-single.py — DO NOT edit this file directly.\n" \
             "  Edit files in src/ (and vendor/), then run: python3 build-single.py\n-->\n"
    html = re.sub(r"<!DOCTYPE html>\n", "<!DOCTYPE html>\n" + banner, html, count=1)

    out = ROOT / "index.html"
    out.write_text(html, encoding="utf-8")
    size_kb = out.stat().st_size / 1024

    # ---- sanity checks ----
    assert 'src="vendor/' not in html, "leftover external vendor reference"
    assert 'href="css/' not in html, "leftover external css reference"
    assert "<style>" in html and "script-src 'unsafe-inline'" in html
    assert 'id="ct-pdf-worker"' in html

    # real parse: confirms escaping holds and finds every script block
    from html.parser import HTMLParser

    class ScriptCounter(HTMLParser):
        def __init__(self):
            super().__init__(convert_charrefs=False)
            self.scripts = []
        def handle_starttag(self, tag, attrs):
            if tag == "script":
                self.scripts.append(dict(attrs))

    p = ScriptCounter()
    p.feed(html)
    p.close()
    expected = len(chunks)
    assert len(p.scripts) == expected, "expected %d script blocks, parsed %d" % (expected, len(p.scripts))
    assert any(s.get("id") == "ct-pdf-worker" and s.get("type") == "text/plain" for s in p.scripts), \
        "worker text block missing"
    assert all("src" not in s for s in p.scripts), "external script reference remains"

    print("✓ Built index.html (%.0f KB) — %d inline script blocks, parses cleanly, self-contained ✓"
          % (size_kb, len(p.scripts)))


if __name__ == "__main__":
    main()
